// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Models.proto

package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户模型
type UserInfo struct {
	// @inject_tag: checking:"required,CheckName"
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" checking:"required,CheckName"`
	UserScore            int32    `protobuf:"varint,2,opt,name=user_score,json=userScore,proto3" json:"user_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_Models_7dbe96f4ec8136e5, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetUserScore() int32 {
	if m != nil {
		return m.UserScore
	}
	return 0
}

type UserScoreRequest struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserScoreRequest) Reset()         { *m = UserScoreRequest{} }
func (m *UserScoreRequest) String() string { return proto.CompactTextString(m) }
func (*UserScoreRequest) ProtoMessage()    {}
func (*UserScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_Models_7dbe96f4ec8136e5, []int{1}
}
func (m *UserScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScoreRequest.Unmarshal(m, b)
}
func (m *UserScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScoreRequest.Marshal(b, m, deterministic)
}
func (dst *UserScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScoreRequest.Merge(dst, src)
}
func (m *UserScoreRequest) XXX_Size() int {
	return xxx_messageInfo_UserScoreRequest.Size(m)
}
func (m *UserScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserScoreRequest proto.InternalMessageInfo

func (m *UserScoreRequest) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserScoreResponse struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserScoreResponse) Reset()         { *m = UserScoreResponse{} }
func (m *UserScoreResponse) String() string { return proto.CompactTextString(m) }
func (*UserScoreResponse) ProtoMessage()    {}
func (*UserScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_Models_7dbe96f4ec8136e5, []int{2}
}
func (m *UserScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScoreResponse.Unmarshal(m, b)
}
func (m *UserScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScoreResponse.Marshal(b, m, deterministic)
}
func (dst *UserScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScoreResponse.Merge(dst, src)
}
func (m *UserScoreResponse) XXX_Size() int {
	return xxx_messageInfo_UserScoreResponse.Size(m)
}
func (m *UserScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserScoreResponse proto.InternalMessageInfo

func (m *UserScoreResponse) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "services.UserInfo")
	proto.RegisterType((*UserScoreRequest)(nil), "services.UserScoreRequest")
	proto.RegisterType((*UserScoreResponse)(nil), "services.UserScoreResponse")
}

func init() { proto.RegisterFile("Models.proto", fileDescriptor_Models_7dbe96f4ec8136e5) }

var fileDescriptor_Models_7dbe96f4ec8136e5 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf1, 0xcd, 0x4f, 0x49,
	0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0x2d, 0x56, 0x72, 0xe2, 0xe2, 0x08, 0x2d, 0x4e, 0x2d, 0xf2, 0xcc, 0x4b, 0xcb, 0x17, 0x12,
	0xe7, 0x62, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d,
	0x62, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x64, 0xb9, 0xb8, 0xc0, 0x12, 0xc5, 0xc9, 0xf9, 0x45, 0xa9,
	0x12, 0x4c, 0x60, 0x39, 0x4e, 0x90, 0x48, 0x30, 0x48, 0x40, 0xc9, 0x86, 0x4b, 0x20, 0x14, 0xc6,
	0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xd2, 0xe0, 0x62, 0x05, 0x29, 0x28, 0x96, 0x60,
	0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd2, 0x83, 0xd9, 0xa8, 0x07, 0xb3, 0x2e, 0x08, 0xa2, 0x40,
	0xc9, 0x96, 0x4b, 0x10, 0x49, 0x77, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0xf1, 0xda, 0x93, 0xd8,
	0xc0, 0x3e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xd3, 0x0a, 0xa7, 0xe1, 0x00, 0x00,
	0x00,
}
